# Generated by Django 5.1.2 on 2024-10-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.TextField()),
                ('lancamento', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
